<?php

namespace AppBundle\Repository;

/**
 * AssuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssuranceRepository extends \Doctrine\ORM\EntityRepository{
    public function getListeAlerteAssurances($seuilAssurance){
        $d=date('y-m-d');
        /*$q=$this->_em->createQuery("SELECT a.dateDebut,a.dateFin,v.nom,date_diff(a.dateFin,:d) as nbrjours FROM AppBundle:Assurance a JOIN a.vehicule v WHERE (v.active=1) AND (a.dernier=1) AND (date_diff(a.dateFin,:d)<=:seuil) ORDER BY nbrjours DESC");
        $q->setParameter('d',$d);
        $q->setParameter('seuil',$seuilAssurance);
        return $q->getResult();*/
/*
        SELECT v.id,v.nom,DATEDIFF(MAX(`date_fin`),:d) 
        FROM `assurance` ,vehicule
        WHERE assurance.vehicule_id=vehicule.id
        GROUP BY `vehicule_id`
        ORDER BY vehicule.id
*/
        $q=$this->_em->createQuery(
            "SELECT v.id,v.nom,date_diff(max(a.dateFin),:d) as nbrjours 
            FROM AppBundle:Assurance a 
            JOIN a.vehicule v 
            WHERE (v.active=1) 
            GROUP BY v.id
            ORDER BY v.nom");
        $q->setParameter('d',$d);
        return $q->getResult();

    }
}
