<?php

namespace AppBundle\Repository;

/**
 * BcPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
