<?php

namespace AppBundle\Repository;

/**
 * BcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcRepository extends \Doctrine\ORM\EntityRepository
{
}
