<?php

namespace AppBundle\Repository;

/**
 * BcResponsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcResponsableRepository extends \Doctrine\ORM\EntityRepository
{
}
