<?php

namespace AppBundle\Repository;

/**
 * BcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeBcs()
    {
        $q = $this->createQueryBuilder('bc')
                ->join('bc.projet','p')
                ->leftJoin('bc.po','po')
                ->join('bc.responsableBc','r')
                ->join('p.client','c')
        ;
        return $q;
    }
}
