<?php

namespace AppBundle\Repository;

/**
 * ControleTechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleTechRepository extends \Doctrine\ORM\EntityRepository
{
}
