<?php
namespace AppBundle\Repository;
/**
 * EntretienVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienVehiculeRepository extends \Doctrine\ORM\EntityRepository
{   
    public function getEntretiens()
    {   
        $q = $this->createQueryBuilder('e');
        $q  ->join('e.user','u')
            ->join('e.vehicule','v')
            ;
        return $q;//->getQuery()->getResult();
    }
    public function getPreview($entretien)
    {   
        $q = $this->createQueryBuilder('e');
        $q  ->where('e.date < :d')
            ->join('e.vehicule','v')
            ->andWhere('v.id =:v')
            ->orderBy('e.date','DESC')
            ->setParameter('d', $entretien->getDate())
            ->setParameter('v', $entretien->getVehicule())
            ;
        $res = $q->getQuery()->getResult();
        if ($res != null) {
            $res = $res [0];
        }else{
            return null;
        }
        return $res;
    }
    public function getNext($entretien)
    {   
        $q = $this->createQueryBuilder('e');
        $q  ->where('e.date > :d')
            ->join('e.vehicule','v')
            ->andWhere('v.id =:v')
            ->orderBy('e.date','ASC')
            ->setParameter('d', $entretien->getDate())
            ->setParameter('v', $entretien->getVehicule())
            ;
        $res = $q->getQuery()->getResult();
        if ($res != null) {
            $res = $res [0];
        }else{
            return null;
        }
        return $res;
    }
    public function getLastEntretien($vehicule)
    {   
        $q = $this->createQueryBuilder('e');
        $q  ->join('e.vehicule','v')
            ->where('v.id =:v')
            ->orderBy('e.date','DESC')
            ->setParameter('v', $vehicule) 
            ;
        $res = $q->getQuery()->getResult();
        if (count($res)>0) {
            return $res[0];
        }else{
            return null;
        }
    }
}
