<?php

namespace AppBundle\Repository;

/**
 * EntretienVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienVehiculeRepository extends \Doctrine\ORM\EntityRepository
{   public function getEntretiens()
    {   
        $q = $this->createQueryBuilder('e');
        $q  ->join('e.user','u')
            ->join('e.vehicule','v')
            ;
        
            
        return $q;//->getQuery()->getResult();
    }
}
