<?php

namespace AppBundle\Repository;

/**
 * FamilleDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
