<?php

namespace AppBundle\Repository;

/**
 * FonctionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionUserRepository extends \Doctrine\ORM\EntityRepository
{
}
