<?php

namespace AppBundle\Repository;

/**
 * InterventionEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionEntretienRepository extends \Doctrine\ORM\EntityRepository
{
}
