<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Form\FormInterface;

/**
 * InterventionEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionEntretienRepository extends \Doctrine\ORM\EntityRepository
{   public function getInterventions()
    {   
        $q = $this->createQueryBuilder('i');
        $q  ->join('i.entretienVehicule','ev')
            ->join('ev.user','u')
            ->join('i.interventionVehicule','iv')
            ->join('ev.vehicule','v')
            ;
        
            
        return $q;//->getQuery()->getResult();
    }
    public function addFilter(QueryBuilder $qb, FormInterface $form)
    {   $vehicule               = $form->get('vehicule')->getData();
        $user                   = $form->get('user')->getData();
        $interventionVehicule   = $form->get('interventionVehicule')->getData();
        if ($user !== null){
            $qb->andWhere('ev.user = :user');
            $qb->setParameter('user',$user);
        }
        if ($vehicule !== null){
            $qb->andWhere('ev.vehicule = :vehicule');
            $qb->setParameter('vehicule',$vehicule);
        }
        if ($interventionVehicule !== null){
            $qb->andWhere('i.interventionVehicule = :interventionVehicule');
            $qb->setParameter('interventionVehicule',$interventionVehicule);
        }

        return $qb;

    }
    
}
