<?php

namespace AppBundle\Repository;

//use AppBundle\Entity\InterventionUser;

/**
 * InterventionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRealisateurs($mission)
    {
        $q = $this->createQueryBuilder('iu');
        $q  ->join('iu.intervention','i')
            ->join('iu.user','u')
            ->addSelect('u')
            ->where('i.mission = :v1')
            ->setParameter('v1',$mission)
            ;
        return $q->getQuery()->getResult();
    }
    public function getRealisateursIntervention($intervention)
    {
        $q = $this->createQueryBuilder('iu');
        $q  ->join('iu.user','u')
            ->addSelect('u')
            ->where('iu.intervention = :v1')
            ->setParameter('v1',$intervention)
            ;
        return $q->getQuery()->getResult();
    }
    public function getInterventionsAll()
    {
        $q = $this->createQueryBuilder('iu');
        $q  ->join('iu.intervention','i')
            ->join('i.prestation','p')
            ->join('i.site','s')
            ->join('iu.user','u')
            ->join('i.mission','m')
            ->join('s.wilaya','w')
            ->join('p.sousProjet','sp')
            ->addSelect('i')
            ->addSelect('p')
            ->addSelect('s')
            ->addSelect('w')
            ->addSelect('sp')
            ->addSelect("GROUP_CONCAT(DISTINCT u.nom SEPARATOR ', ') AS acompagnateur")
            ;
        return $q;
    }

    public function getInterventionsDate($date)
    {
        $q = $this->createQueryBuilder('iu');
        $q  ->join('iu.user','u')
            ->join('iu.intervention','i')
            ->join('i.site','s')
            ->join('s.wilaya','w')
            ->addSelect('u')
            //->addSelect("GROUP_CONCAT(DISTINCT w.nom SEPARATOR ', ') AS destination")
            ->where('i.dateIntervention = :d')
            ->orderBy('u.id')
            ->setParameter('d',$date)
            ;
        return $q->getQuery()->getResult();
    }



}
