<?php

namespace AppBundle\Repository;

/**
 * JustificationDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificationDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
