<?php

namespace AppBundle\Repository;

/**
 * KmsInterventionVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KmsInterventionVehiculeRepository extends \Doctrine\ORM\EntityRepository
{ 
    

}
