<?php

namespace AppBundle\Repository;

/**
 * LicenciementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciementRepository extends \Doctrine\ORM\EntityRepository
{   /**
     * id licenciement
     */
    public function getLicenciement($id)
    {
        $q=$this->createQueryBuilder('l')
                ->join('l.recrutement','r','WITH','l.id = :id')
                ->join('r.user','u')
                ->addSelect('u')
                //->LeftJoin('','WITH','r.user = :id')
                ->addSelect('r')
                //->leftJoin('da.description','d')
                //->where('d.id IS NULL')
                //->addSelect('d')
                ->setParameters(array('id'=>$id));

        $res = $q->getQuery()->getResult();
        if (count($res)>0)
        {
            return $res[0];
        }else
        {
            return false;
        }
    }
    public function getLicenciementPrecedent($user,$date)
    {   $q=$this->createQueryBuilder('l')
                ->leftJoin('l.recrutement','r','WITH','r.user = :user')
                //->join('r.user','u')
                ->addSelect('r')
                ->where('r.recruter < :d')
                ->setParameter('user', $user)
                ->setParameter('d' , $date)
                ;

        $res = $q->getQuery()->getResult();
        if (count($res)>0)
        {
            return $res[count($res)-1];
        }else
        {
            return false;
        }
}
    public function getLicenciementDernier($user)
    {   $q=$this->createQueryBuilder('l')
                ->join('l.recrutement','r','WITH','r.user = :user')
                ->addSelect('r')
                ->setParameter('user', $user)
                ;

        $res = $q->getQuery()->getResult();
        if (count($res)>0)
        {
            return $res[count($res)-1];
        }else
        {
            return false;
        }
    }

}
