<?php

namespace AppBundle\Repository;

/**
 * PointageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPointages($v = null)
    {   
        $q = $this->createQueryBuilder('p');
        $q  ->join('p.user','u')
            ;
        if ($v==1)
        {
            $d = new \DateTime("now");
            $q->where('p.date = :d');
            $q->setParameter('d', $d);
        }
            
        return $q;//->getQuery()->getResult();
    }
}
