<?php

namespace AppBundle\Repository;

/**
 * PointageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageUserRepository extends \Doctrine\ORM\EntityRepository
{
}
