<?php

namespace AppBundle\Repository;

/**
 * PointageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageRepository extends \Doctrine\ORM\EntityRepository
{
}
