<?php

namespace AppBundle\Repository;

/**
 * poRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class poRepository extends \Doctrine\ORM\EntityRepository
{
}
