<?php

namespace AppBundle\Repository;

/**
 * PrestationBcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationBcRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSomme($bc)
    {   
        $q = $this->createQueryBuilder('p')
<<<<<<< HEAD
        ->select('SUM(p.montant * p.quantite) AS somme')
=======
        ->select('SUM(p.montant * p.qte) AS somme')
>>>>>>> c4c86e1f6dacdb75bcb034443d12a868987ff8f1
        ->where('p.bc = :bc')
        ->setParameter('bc',$bc);
        ;
        //return $q->getQuery()->getResult()[0];
        return $q->getQuery()->getSingleScalarResult();

    }

<<<<<<< HEAD
    public function findPrestationIntervention($bc,$prestation,$zone)
    {
        $q = $this->createQueryBuilder('pb')
            ->join('pb.bc','bc')
            ->join('pb.prestation','p')
            ->join('pb.zone','z')
            ->where('bc = :bc')
            ->andWhere('p = :prestation')
            ->andWhere('z = :zone')
            ->setParameter('bc',$bc)
            ->setParameter('prestation',$prestation)
            ->setParameter('zone',$zone)
            ;
        return $q->getQuery()->getResult();

    }
    

=======
>>>>>>> c4c86e1f6dacdb75bcb034443d12a868987ff8f1
}
