<?php

namespace AppBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjets(){
        $q = $this->createQueryBuilder('p');
        $q  ->join('p.client','c')
            ;
        return $q;
    }
}
