<?php
namespace AppBundle\Repository;
/**
 * RecrutementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementRepository extends \Doctrine\ORM\EntityRepository
{
    public function test()
    {
        return "ok";
    }
    public function getRecrutementSuivants($user,$date)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $q = $this->createQueryBuilder('r')
            ->join('r.user','u')
            ->where('r.recruter > :d')
            ->andWhere('u.id = :user')
            ->setParameter('d', $date)
            ->setParameter('user',$user)
            ->orderBy('r.recruter', 'ASC')
            ->getQuery();
        $res = $q->getResult();
        if (count($res)>0)
        {
            return $res[0];
        }else
        {
            return false;
        }
    }

    public function getRecrutementPrecedents($user,$date)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $q = $this->createQueryBuilder('r')
            ->join('r.user','u')
            ->where('r.recruter < :d')
            ->andWhere('u.id = :user')
            ->setParameter('d', $date)
            ->setParameter('user',$user)
            ->orderBy('r.recruter', 'ASC')
            ->getQuery();
        $res = $q->getResult();
        if (count($res)>0)
        {
            return $res[count($res)-1];
        }else
        {
            return false;
        }
    }
 
    public function listeRecrutement($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT r.id,l.id as idlicenciement,r.recruter,l.licencier,l.motif FROM AppBundle:Recrutement r LEFT JOIN AppBundle:Licenciement l  WITH r.id = l.recrutement WHERE r.user = ?1");
        $query->setParameter(1, $id);
        $res = $query->getResult();
        return $res;
    }
    public function getRecrutementFonction($user,$recruter)
    {
        //$em = $this->getEntityManager();
        //$qb = $em->createQueryBuilder();
        $q = $this->createQueryBuilder('r')
            ->leftJoin('r.licenciement','l','WITH','r.user = :user')
            ->where('r.recruter >= :recruter')
//            ->andWhere('u.id = :user')
            ->setParameter('recruter', $recruter)
            ->setParameter('user',$user)
            ->orderBy('r.recruter', 'ASC')
            ->getQuery();
        $res = $q->getResult();
        return $res;

    }
}
