<?php

namespace AppBundle\Repository;

/**
 * ResponsableBcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableBcRepository extends \Doctrine\ORM\EntityRepository
{
}
