<?php
namespace AppBundle\Repository;
use Doctrine\ORM\Query;
/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSitess($client,$site,$startRow,$maxRows)
    {   
        $q = $this->createQueryBuilder('s');
        $q  ->select('s.id','s.code','s.nom')
            ->join('s.client','c')
            ->addSelect('c.nom as client');
        $q  ->where('s.client = :client');
        if ($site !== null)
        {
            $q  ->andWhere($q->expr()->orX(
                $q->expr()->like('s.code', $q->expr()->literal('%'.$site.'%')),
                $q->expr()->like('s.nom', $q->expr()->literal('%'.$site.'%'))));
        }
        $q  ->setFirstResult( $startRow )
            ->setMaxResults( $maxRows );
        $q  ->orderby('s.code','ASC')
            ->setParameter('client', $client);
        return $q;
    }
    public function getTotalRows($client,$site)
    {   
        $q = $this->createQueryBuilder('s')
            ->select('count(s)')
            ->join('s.client','c')
            ->where('s.client = :client');
            if ($site !== null)
            {
                $q  ->andWhere($q->expr()->orX(
                    $q->expr()->like('s.code', $q->expr()->literal('%'.$site.'%')),
                    $q->expr()->like('s.nom', $q->expr()->literal('%'.$site.'%'))));
            }
        $q  ->setParameter('client', $client);
        $q = $q->getQuery()->getResult(Query::HYDRATE_SINGLE_SCALAR);
        return $q;
    }
}
