<?php

namespace AppBundle\Repository;

/**
 * SousProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
