<?php

namespace AppBundle\Repository;

/**
 * TableFraisMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableFraisMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
