<?php

namespace AppBundle\Repository;

/**
 * TarifPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
