<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function test($d1,$d2)
    {
        $q=$this->createQueryBuilder('t')
                ->where('t.date BETWEEN :d1 AND :d2')
                ->setParameter('d1', $d1)
                ->setParameter('d2', $d2);

        return $q->getQuery()->getResult();
        
    }
}
