<?php

namespace AppBundle\Repository;

/**
 * WilayaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WilayaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWilayas()
    {
        $qb = $this->createQueryBuilder('w')
                    ->join('w.zone','z')
        ;
        return $qb;
    }
}
