<?php

namespace AppBundle\Entity;

/**
 * AssuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssuranceRepository extends \Doctrine\ORM\EntityRepository
{
}
