<?php

namespace AppBundle\Entity;

/**
 * ControletechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControletechRepository extends \Doctrine\ORM\EntityRepository
{
}
