<?php

namespace AppBundle\Entity;

/**
 * InterventionVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
