<?php

namespace AppBundle\Entity;

/**
 * KmsIterventionVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KmsIterventionVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
